FROM nazarpc/php:fpm
LABEL maintainer "Nazar Mokrynskyi <nazar@mokrynskyi.com>"

RUN \

	apt-get update && \
	apt-get upgrade -y && \

# Ceph repository for up to date version of ceph-fuse package; Ceph itself is used as cluster filesystem

	CEPH_VERSION=kraken && \
	curl -sSL 'https://download.ceph.com/keys/release.asc' | apt-key add - && \
	echo "deb http://download.ceph.com/debian-$CEPH_VERSION/ jessie main" > /etc/apt/sources.list.d/ceph-$CEPH_VERSION.list && \
	apt-get update && \
	apt-get install -y --no-install-recommends ceph-fuse && \

	apt-get clean && \
	rm -rf /var/lib/apt/lists/* && \

# Change PHP-FPM user

	sed -i 's/www-data/git/g' /usr/local/etc/php-fpm.d/www.conf && \

	mv /usr/local/etc /usr/local/etc_dist

COPY common /webserver-common/
RUN /webserver-common/create-git-user.sh

COPY php-fpm/webserver-entrypoint.sh /

VOLUME \
	/data \
	/usr/local/etc

ENV \
	CEPH_MON_SERVICE=ceph-mon \
	CEPHFS_MOUNT=0

ENTRYPOINT ["/webserver-entrypoint.sh"]

CMD ["php-fpm"]
