FROM nginx:1
LABEL maintainer "Nazar Mokrynskyi <nazar@mokrynskyi.com>"

RUN \

	apt-get update && \
	apt-get upgrade -y && \

# Ceph repository for up to date version of ceph-fuse package; Ceph itself is used as cluster filesystem

	CEPH_VERSION=kraken && \
	apt-get install -y --no-install-recommends curl ca-certificates && \
	curl -sSL 'https://download.ceph.com/keys/release.asc' | apt-key add - && \
	echo "deb http://download.ceph.com/debian-$CEPH_VERSION/ jessie main" > /etc/apt/sources.list.d/ceph-$CEPH_VERSION.list && \
	apt-get update && \
	apt-get install -y --no-install-recommends ceph-fuse && \
	apt-get purge -y --auto-remove curl ca-certificates && \

	apt-get clean && \
	rm -rf /var/lib/apt/lists/* && \

# Run in foreground (let's specify it config file, since dealing with parameters that contain spaces is more difficult than we'd like it to be)

	echo "daemon off;\n$(cat /etc/nginx/nginx.conf)" > /etc/nginx/nginx.conf && \

# Change Nginx user

	sed -i 's/user  nginx;/user  git;/g' /etc/nginx/nginx.conf && \

# Make Nginx work with PHP with default config

	sed -i 's/127.0.0.1:9000/php:9000/g' /etc/nginx/conf.d/default.conf && \

# We'll keep configs in /data/nginx/config

	sed -i 's/\/etc\/nginx/\/data\/nginx\/config/g' `find /etc/nginx -type f` && \

# We'll keep logs in /data/nginx/log if CephFS is not used and local directory otherwise

	sed -i 's/\/var\/log\/nginx/\/data\/nginx\/log/g' `find /etc/nginx -type f` && \

# We'll keep data in /data/nginx/www

	sed -i 's/\/usr\/share\/nginx\/html/\/data\/nginx\/www/g' `find /etc/nginx -type f` && \

	mv /etc/nginx /etc/nginx_dist

COPY common /webserver-common/
RUN /webserver-common/create-git-user.sh

COPY nginx/webserver-entrypoint.sh /

VOLUME \
	/data \
	/tmp

ENV \
	CEPH_MON_SERVICE=ceph-mon \
	CEPHFS_MOUNT=0

ENTRYPOINT ["/webserver-entrypoint.sh"]

CMD ["nginx"]
