FROM phusion/baseimage:0.9.19
LABEL maintainer "Nazar Mokrynskyi <nazar@mokrynskyi.com>"

COPY webserver-common /webserver-common/

RUN \

	/webserver-common/create-git-user.sh && \

	/webserver-common/apt-get-update.sh && \
	/webserver-common/apt-get-install-common.sh && \
	/webserver-common/apt-get-install-ceph-fuse.sh && \

	apt-get install -y --no-install-recommends git mc wget php-cli && \

	/webserver-common/apt-get-cleanup.sh && \

# Enable SSH

	rm -f /etc/service/sshd/down && \

# Rename SSH config directory

	mv /etc/ssh /etc/ssh_dist && \

# Install Composer

	COMPOSER_VERSION=1.3.2 && \
	curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer --version=$COMPOSER_VERSION

COPY ssh/webserver-entrypoint.sh /

ENV \
	CEPH_MON_SERVICE=ceph-mon \
	CEPHFS_MOUNT=0 \

	TERM=xterm

VOLUME \
	/data \
	/etc/ssh

ENTRYPOINT ["/webserver-entrypoint.sh"]
